/*
THIS PROJECT USES AIE (ACADEMY OF INTERACTIVE ENTERTAINMENT) BOOTSTRAP CODEBASE AS A FOUNDATION FOR CERTAIN OPENGL BASED
OBJECTS AND LOGIC SUCH AS WINDOW, INPUT, RENDERING PRIMITIVES AND MORE.

I (Rabbet) DO NOT TAKE CREDIT FOR THESE PARTS OF MY PROJECT AND THEY ARE CREATED AND DEVELOPED BY AIE.

AIE BOOTSTRAP IS A PUBLIC, OPEN SOURCE, M.I.T LISCENCED LIBRARY AVAILABLE PUBLICALLY AT THEIR GITHUB REPOSITORY:

https://github.com/AcademyOfInteractiveEntertainment/aieBootstrap
*/

#include "Application3D.h"

int main() 
{
	Application3D::start();
	Application3D::deleteInstance();
	return 0;
}